import type { QuickFilter, ReceptionOrder } from "./types";

export const QUICK_FILTERS: QuickFilter[] = ["Todas", "Hoy", "Urgentes", "Sin muestras", "Listas"];

export const TEST_TO_TUBE: Record<string, string> = {
  Glucosa: "Tubo rojo",
  "Perfil lipídico": "Tubo rojo",
  "Hemograma completo": "Tubo morado",
  Creatinina: "Tubo rojo",
  Uroanálisis: "Frasco estéril",
  "Heces completo": "Frasco heces",
  TSH: "Tubo rojo",
  "BHCG cualitativa": "Tubo rojo",
  Plaquetas: "Tubo morado",
  "Dengue NS1": "Tubo amarillo",
};

export const INITIAL_ORDERS: ReceptionOrder[] = [
  {
    id: "#1042",
    patientName: "Ana López",
    patientAge: 36,
    doctor: "Dr. Hernández",
    tests: ["Glucosa", "Perfil lipídico", "Hemograma completo"],
    priority: "Urgente",
    status: "Sin muestras",
    notes: "Paciente en ayunas desde las 6:00 AM.",
    createdAt: "2026-02-20T12:25:00-06:00",
    isNew: true,
  },
  {
    id: "#1043",
    patientName: "Carlos Mejía",
    patientAge: 51,
    doctor: "Dra. Ruiz",
    tests: ["Creatinina", "Uroanálisis"],
    priority: "Rutina",
    status: "Sin muestras",
    notes: "Orden externa enviada por clínica aliada.",
    createdAt: "2026-02-20T12:13:00-06:00",
  },
  {
    id: "#1044",
    patientName: "María Bonilla",
    patientAge: 28,
    doctor: "Dr. Suazo",
    tests: ["TSH", "BHCG cualitativa"],
    priority: "Urgente",
    status: "Muestras creadas",
    notes: "Esperando toma de muestra en sala 2.",
    createdAt: "2026-02-20T11:45:00-06:00",
  },
  {
    id: "#1045",
    patientName: "Josefina Reyes",
    patientAge: 44,
    doctor: "Dr. Turcios",
    tests: ["Heces completo"],
    priority: "Rutina",
    status: "Procesando",
    notes: "Muestra ya entregada al área técnica.",
    createdAt: "2026-02-20T10:55:00-06:00",
  },
  {
    id: "#1046",
    patientName: "Ernesto Aguilar",
    patientAge: 62,
    doctor: "Dra. Flores",
    tests: ["Plaquetas", "Dengue NS1"],
    priority: "Urgente",
    status: "Sin muestras",
    notes: "Prioridad alta por criterio médico.",
    createdAt: "2026-02-20T12:22:00-06:00",
    isNew: true,
  },
];
