import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import ConfigureAmplifyClientSide from "@/components/ConfigureAmplifyClientSide";

const jakarta = Plus_Jakarta_Sans({
	variable: "--font-jakarta",
	subsets: ["latin", "latin-ext"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${jakarta.variable} font-sans antialiased`}
			>
				<ConfigureAmplifyClientSide />
				<TooltipProvider>{children}</TooltipProvider>
			</body>
		</html>
	);
}
